### ISSUE TITLE
New entity: CLN6 disease Costa Rican variant

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#83] opened 2023-06-21 10:07 UTC
Dear all,

We would like to share with you a request on behalf of a patients association regarding the creation of a CLN6 disease Costa Rican variant. They have provided the following publication as evidence:
https://pubmed.ncbi.nlm.nih.gov/11791207/

Thank you in advance and kind regards,

María Elena

**Comment by Orphanet-MartaFructuoso** [comment] 2023-07-27 15:30
Dear @Orphanet-ES,

Thank you for sharing this information with us.

We recently reviewed the "Neuronal ceroid lipofuscinosis" group (ORPHA:216) since there were disease subtypes under more than one disease. 
In Orphanet a subtype can have only one mother disease. Moreover, the geneticist in Orphanet confirmed that these etiological subtypes are distinguishable only by the genes involved, and doctors can only identify the subtype after having the genetic results. 
Therefore, to solve this incoherence, CLN6, along with the rest of the CLN diseases,  will be soon obsoleted and referred to ORPHA:216. For each CLN disease, the causing gene will be linked to the appropiate ORPHAcode depending of the disease onset.

Specificaly for CLN6 disease, the CLN6 transmembrane ER protein, (CLN6) gene will be linked to the disorders: "Late infantile neuronal ceroid lipofuscinosis" (ORPHA:168491); "Juvenile neuronal ceroid lipofuscinosis" (ORPHA:79264), and "Adult neuronal ceroid lipofuscinosis" (ORPHA:79262).
 
Thank you very much.
Best regards,
Marta

**Comment by LeneMartinsen** [comment] 2023-10-06 06:29
Dear @Orphanet-MartaFructuoso 
I allow myself to jump on this thread, even though it is closed :)
The reason is that I just got a request from a professional in our team (MD. Ingrid B. Helland) that has been using the ORPHAcode for CLN3 and she was surprised to see it gone. She also contacted colleagues in Germany that was baffled about it too. I understand the reason you have given above but it is a bit unfortunate that codes disappear that professionals are actively using. Is this something we could discuss in the OD4RD2 project? @MCecile-US14 ?

All the best,
Lene

**Comment by MCecile-US14** [comment] 2024-02-26 13:26
Dear @Orphanet-MartaFructuoso, 

Could you please resume the actions proceed for this entity (and similar entities  of this group) and follow up with @Orphanet-ES and @LeneMartinsen to clarify what has been done and the rational behind it?
Thank you, 
Marie-Cécile

**Comment by Orphanet-MartaFructuoso** [comment] 2024-02-29 09:11
Dear @LeneMartinsen and @Orphanet-ES ,

Thank you for your messages.
In view of your comments, we will contact and discuss with experts the issue. 

Upon revision of the "Neuronal ceroid lipofuscinosis" group (ORPHA:216), some entities were obsoleted because they appeared as subtypes of more than one disease. 
Even so, it is worth mentioning that, when an entity is obsoleted, it always has a suggestion of an ORPHAcode for replacement. 

Best regards,
Marta

Best regards,
Marta

**Comment by Orphanet-MartaFructuoso** [comment] 2024-07-05 12:02
Dear @LeneMartinsen,
Before closing this issue, I would like to inform you that the codes for all CLN diseases are active as disorders in the 2024 nomenclature pack. This should fix the coding issues.

Best,
Marta

**Closed** 2024-07-05 12:12 UTC
Labels: Norway, Spain, Creation

**Comment by LeneMartinsen** [comment] 2024-07-10 06:01
Dear Marta,
Thank you very much. I'm sorry, I see that I never got back to you earlier in this thread concerning the professionals claim. I know they found it very useful to be able to distinguish this subtype (CLN3) from other subtypes. If you need, I can put it in my calendar to clarify it more over the summer?

Kind regards,
Lene

**Comment by Orphanet-MartaFructuoso** [comment] 2024-07-10 15:21
Dear Lene,
No problem, I don't think it's necessary. 
We have discussed with experts and changed the typology: now CLN diseases are disorders rather than subtypes, with all codes active. 
Kind regards,
Marta
